export enum Nationalities {
    AU = "AU",
    BR = "BR",
    CA = "CA",
    CH = "CH",
    DE = "DE",
    DK = "DK",
    ES = "ES",
    FI = "FI",
    FR = "FR",
    GB = "GB",
    IE = "IE",
    IR = "IR",
    NO = "NO",
    NL = "NL",
    NZ = "NZ",
    TR = "TR",
    US = "US",
}